CREATE TABLE IF NOT EXISTS withdrawals(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  order_id VARCHAR(128) NOT NULL UNIQUE,
  sum NUMERIC(6,2) NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);