DROP TYPE IF EXISTS order_status CASCADE;
CREATE TYPE order_status AS ENUM ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED');
CREATE TABLE IF NOT EXISTS orders(
  id VARCHAR(128) PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  accrual NUMERIC(6,2) NOT NULL DEFAULT 0,
  status order_status NOT NULL DEFAULT 'NEW'
);